language: node_js
node_js:
  - "10"

before_deploy:
  - npm run build:gh-pages:prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: "./build"
  on:
    branch: master
    
notifications:
  slack: akropolisio:xUhLQpSGEoBylmWK3DW8Kblm

